import { beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import {
  buildOrchestrationDiagramState,
  convertToOrchestrationStep,
  mapStatusString,
  mapRoleString,
} from "../orchestration-diagram-utils";

vi.mock("#/utils/mermaid-generator", () => {
  const autoGenerateDiagram = vi.fn(
    (_id: string, _role: string, artifact?: Record<string, any>) => {
      if (!artifact?.diagramType) return undefined;
      return {
        type: artifact.diagramType,
        mermaid: `graph TD; ${artifact.diagramType}`,
      };
    },
  );

  return {
    autoGenerateDiagram,
    generateOrchestrationFlow: vi.fn(() => "graph TD; overview"),
    generateApiSequenceDiagram: vi.fn(() => "sequenceDiagram"),
  };
});

vi.mock("#/utils/artifact-parser", () => ({
  parseArtifact: vi.fn((_artifact: Record<string, any>, role: string) => ({
    parsed: true,
    role,
  })),
}));

type MermaidGeneratorModule = {
  autoGenerateDiagram: ReturnType<typeof vi.fn>;
  generateOrchestrationFlow: ReturnType<typeof vi.fn>;
  generateApiSequenceDiagram: ReturnType<typeof vi.fn>;
};

let mermaidGenerator: MermaidGeneratorModule;

beforeAll(async () => {
  mermaidGenerator = (await import("#/utils/mermaid-generator")) as MermaidGeneratorModule;
});

describe("orchestration-diagram-utils", () => {
  beforeEach(() => {
    mermaidGenerator.autoGenerateDiagram.mockClear();
    mermaidGenerator.generateApiSequenceDiagram.mockClear();
  });

  it("builds diagram state with derived diagrams and tabs", () => {
    const steps = [
      {
        step_id: "architect",
        role: "Lead Architect",
        status: "success",
        artifact: { diagramType: "architecture" },
      },
      {
        step_id: "qa",
        role: "QA",
        status: "running",
        artifact: { diagramType: "gantt-chart" },
      },
    ];

    const state = buildOrchestrationDiagramState(steps, true);

    expect(state.architectureDiagram).toBe("graph TD; architecture");
    expect(state.timelineDiagram).toBe("graph TD; gantt-chart");
    expect(state.apiDiagram).toBe("sequenceDiagram");
    expect(state.tabs.map((tab) => tab.id)).toEqual([
      "flow",
      "agents",
      "overview",
      "architecture",
      "api",
      "timeline",
      "raw",
    ]);
  });

  it("filters flow-based tabs when there are no steps", () => {
    const state = buildOrchestrationDiagramState([], false);
    expect(state.tabs.map((tab) => tab.id)).toEqual(["overview", "raw"]);
    expect(state.apiDiagram).toBeUndefined();
  });

  it("calls API sequence generator when architect step is present", () => {
    const steps = [
      { step_id: "1", role: "Architect", status: "success", artifact: {} },
    ];

    buildOrchestrationDiagramState(steps, true);
    expect(mermaidGenerator.generateApiSequenceDiagram).toHaveBeenCalledTimes(1);
  });

  it("converts raw steps into orchestration steps", () => {
    const step = {
      step_id: "123",
      role: "QA",
      status: "running",
      artifact: { foo: "bar" },
      title: "QA Validation",
    };

    const converted = convertToOrchestrationStep(step);

    expect(converted).toMatchObject({
      id: "123",
      role: "qa",
      status: "in_progress",
      title: "QA Validation",
    });
    expect(converted.artifact).toMatchObject({ role: "qa" });
  });

  it("normalizes roles and statuses via mapping helpers", () => {
    expect(mapRoleString("Product Manager")).toBe("product_manager");
    expect(mapRoleString("Platform-Engineer")).toBe("engineer");
    expect(mapStatusString("success")).toBe("complete");
    expect(mapStatusString("blocked")).toBe("blocked");
    expect(mapStatusString("pending")).toBe("pending");
  });
});


