"""Data models describing outputs generated by the resolver workflows."""

from __future__ import annotations

from typing import Any
from dataclasses import dataclass

from forge.resolver.interfaces.issue import Issue


@dataclass
class ResolverOutput:
    """Structured representation of resolver results to display or export."""

    issue: Issue
    issue_type: str
    instruction: str
    base_commit: str
    git_patch: str
    history: list[dict[str, Any]]
    metrics: dict[str, Any] | None
    success: bool
    comment_success: list[bool] | None
    result_explanation: str
    error: str | None


__all__ = ["ResolverOutput", "Issue"]
