import json
from unittest.mock import MagicMock, patch
from forge.core.config import LLMConfig
from forge.events.action.message import MessageAction
from forge.llm import LLM
from forge.resolver.interfaces.gitlab import GitlabIssueHandler, GitlabPRHandler
from forge.resolver.interfaces.issue import Issue
from forge.resolver.interfaces.issue_definitions import (
    ServiceContextIssue,
    ServiceContextPR,
)


def test_guess_success_multiline_explanation():
    issue = Issue(
        owner="test",
        repo="test",
        number=1,
        title="Test Issue",
        body="Test body",
        thread_comments=None,
        review_comments=None,
    )
    history = [MessageAction(content="Test message")]
    llm_config = LLMConfig(model="test", api_key="test")
    mock_response = MagicMock()
    mock_response.choices = [
        MagicMock(
            message=MagicMock(
                content="--- success\ntrue\n\n--- explanation\nThe PR successfully addressed the issue by:\n- Fixed bug A\n- Added test B\n- Updated documentation C\n\nAutomatic fix generated by Forge 🙌"
            )
        )
    ]
    with patch.object(LLM, "completion", return_value=mock_response) as mock_completion:
        handler = ServiceContextIssue(
            GitlabIssueHandler("test", "test", "test"), llm_config
        )
        success, _, explanation = handler.guess_success(issue, history)
        assert success is True
        assert "The PR successfully addressed the issue by:" in explanation
        assert "Fixed bug A" in explanation
        assert "Added test B" in explanation
        assert "Updated documentation C" in explanation
        assert "Automatic fix generated by Forge" in explanation
        mock_completion.assert_called_once()


def test_pr_handler_guess_success_with_thread_comments():
    llm_config = LLMConfig(model="test", api_key="test")
    handler = ServiceContextPR(GitlabPRHandler("test", "test", "test"), llm_config)
    issue = Issue(
        owner="test-owner",
        repo="test-repo",
        number=1,
        title="Test PR",
        body="Test Body",
        thread_comments=["First comment", "Second comment"],
        closing_issues=["Issue description"],
        review_comments=None,
        thread_ids=None,
        head_branch="test-branch",
    )
    history = [MessageAction(content="Fixed the issue by implementing X and Y")]
    llm_config = LLMConfig(model="test-model", api_key="test-key")
    mock_response = MagicMock()
    mock_response.choices = [
        MagicMock(
            message=MagicMock(
                content="--- success\ntrue\n\n--- explanation\nThe changes successfully address the feedback."
            )
        )
    ]
    with patch.object(LLM, "completion", return_value=mock_response):
        success, success_list, explanation = handler.guess_success(issue, history)
        assert success is True
        assert success_list == [True]
        assert "successfully address" in explanation
        assert len(json.loads(explanation)) == 1


def test_pr_handler_guess_success_only_review_comments():
    llm_config = LLMConfig(model="test", api_key="test")
    handler = ServiceContextPR(
        GitlabPRHandler("test-owner", "test-repo", "test-token"), llm_config
    )
    issue = Issue(
        owner="test-owner",
        repo="test-repo",
        number=1,
        title="Test PR",
        body="Test Body",
        thread_comments=None,
        closing_issues=["Issue description"],
        review_comments=["Please fix the formatting", "Add more tests"],
        thread_ids=None,
        head_branch="test-branch",
    )
    history = [MessageAction(content="Fixed the formatting and added more tests")]
    llm_config = LLMConfig(model="test-model", api_key="test-key")
    mock_response = MagicMock()
    mock_response.choices = [
        MagicMock(
            message=MagicMock(
                content="--- success\ntrue\n\n--- explanation\nThe changes successfully address the review comments."
            )
        )
    ]
    with patch.object(LLM, "completion", return_value=mock_response):
        success, success_list, explanation = handler.guess_success(issue, history)
        assert success is True
        assert success_list == [True]
        assert (
            '["The changes successfully address the review comments."]' in explanation
        )


def test_pr_handler_guess_success_no_comments():
    llm_config = LLMConfig(model="test", api_key="test")
    handler = ServiceContextPR(GitlabPRHandler("test", "test", "test"), llm_config)
    issue = Issue(
        owner="test-owner",
        repo="test-repo",
        number=1,
        title="Test PR",
        body="Test Body",
        thread_comments=None,
        closing_issues=["Issue description"],
        review_comments=None,
        thread_ids=None,
        head_branch="test-branch",
    )
    history = [MessageAction(content="Fixed the issue")]
    llm_config = LLMConfig(model="test-model", api_key="test-key")
    success, success_list, explanation = handler.guess_success(issue, history)
    assert success is False
    assert success_list is None
    assert explanation == "No feedback was found to process"
