<#
update-snapshot.ps1
Usage: .\scripts\update-snapshot.ps1 -SourcePath <path-to-openhands-root> -SnapshotPath <path-to-snapshot-root>

This script copies the main repo into the cleaned snapshot folder, applies cleanup rules
(remove nested .git, remove node_modules, remove vendor folders), updates .gitignore,
creates a commit on the current branch and pushes it upstream.

Default behavior assumes you run it from inside the snapshot repo and provide the source path
(e.g. the parent folder where the real OpenHands repo lives).
#>
param(
    [string]$SourcePath = "..\OpenHands",
    [string]$SnapshotPath = ".",
    [switch]$DryRun
)

function Write-Log { param($m) Write-Host "[update-snapshot] $m" }

# Resolve absolute paths
$SourcePath = Resolve-Path -Path $SourcePath
$SnapshotPath = Resolve-Path -Path $SnapshotPath
Write-Log "Source: $SourcePath"
Write-Log "Snapshot: $SnapshotPath"

# Safety: prevent copying snapshot into itself
if ($SourcePath -eq $SnapshotPath) { Write-Log "Source and Snapshot are the same path — aborting."; exit 1 }

# Files/dirs to exclude from copy (relative to source)
$exclude = @(
    ".git",
    "frontend/node_modules",
    "**/__pycache__",
    "**/.pytest_cache",
    ".venv",
    ".venv2"
)

# Helper to delete path if exists in snapshot
function Remove-IfExists($path) { if (Test-Path $path) { Remove-Item -Recurse -Force $path; Write-Log "Removed $path" } }

# 1) Copy files from source to snapshot (preserve tree, skip excludes)
Write-Log "Copying files from source to snapshot..."
if ($DryRun) { Write-Log "Dry run: skipping file copy" } else {
    # We'll copy all top-level items from source into snapshot, overwriting existing files.
    Get-ChildItem -Path $SourcePath -Force | ForEach-Object {
        $name = $_.Name
        if ($exclude -contains $name) { Write-Log "Skipping excluded top-level: $name"; return }
        $dest = Join-Path $SnapshotPath $name
        # Use robocopy for robust directory copy
        if ($_.PSIsContainer) {
            Write-Log "Copying dir $($_.FullName) -> $dest"
            robocopy $_.FullName $dest /MIR /NFL /NDL /NJH /NJS | Out-Null
        } else {
            Write-Log "Copying file $($_.FullName) -> $dest"
            Copy-Item -Path $_.FullName -Destination $dest -Force
        }
    }
}

# 2) Cleanup: remove nested .git directories that might have been copied
Write-Log "Cleaning nested .git dirs..."
if (-not $DryRun) {
    $nestedGits = Get-ChildItem -Path $SnapshotPath -Recurse -Force -Directory -ErrorAction SilentlyContinue | Where-Object { $_.Name -eq '.git' }
    foreach ($g in $nestedGits) { Remove-Item -Recurse -Force $g.FullName; Write-Log "Removed nested .git: $($g.FullName)" }
}

# 3) Remove frontend/node_modules if present
$nm = Join-Path $SnapshotPath "frontend\node_modules"
if (Test-Path $nm) { Remove-Item -Recurse -Force $nm; Write-Log "Removed frontend/node_modules" }

# 4) Ensure .gitignore has usual local excludes
$gitignore = Join-Path $SnapshotPath ".gitignore"
$ignoreLines = @(
    "# local virtualenvs",
    ".venv/",
    ".venv2/",
    "# node modules",
    "/frontend/node_modules/",
    "# Byte-compiled / caches",
    "**/__pycache__/",
    ".pytest_cache/"
)
if ($DryRun) { Write-Log "Dry run: skipping .gitignore update" } else {
    if (-not (Test-Path $gitignore)) { "# generated by update-snapshot.ps1`n" | Out-File -FilePath $gitignore -Encoding utf8 }
    $existing = Get-Content -Path $gitignore -ErrorAction SilentlyContinue
    foreach ($line in $ignoreLines) { if ($existing -notcontains $line) { Add-Content -Path $gitignore -Value $line; Write-Log "Added to .gitignore: $line" } }
}

# 5) Git commit + push (on current branch in snapshot repo)
Set-Location $SnapshotPath
$branch = (git rev-parse --abbrev-ref HEAD) -replace "`n",""
Write-Log "Current snapshot branch: $branch"
if ($DryRun) { Write-Log "Dry run: skip git commit" } else {
    git add -A
    git commit -m "chore(snapshot): refresh snapshot from source at $(Get-Date -Format o)" || Write-Log "No changes to commit"
    git push
}

Write-Log "Snapshot update complete."
