import React, { useState } from "react";
import { ChevronDown } from "lucide-react";

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ_ITEMS: FAQItem[] = [
  {
    question: "What is OpenHands Beta?",
    answer:
      "OpenHands Beta is an early access version of our AI-powered development platform. You get to try cutting-edge features before they're released to everyone, and your feedback helps shape the product.",
  },
  {
    question: "Is my code and data secure?",
    answer:
      "Absolutely! OpenHands runs entirely on your infrastructure. Your code never leaves your environment. We don't store or transmit your API keys or source code to our servers.",
  },
  {
    question: "What AI models does OpenHands support?",
    answer:
      "OpenHands works with all major AI providers including Anthropic Claude (Sonnet 4, Haiku 4.5), OpenAI (GPT-4o, GPT-4o Mini), Google Gemini, and any custom models. You can switch between models anytime.",
  },
  {
    question: "Do I need to know how to code?",
    answer:
      "Not necessarily! OpenHands can write code for you based on natural language descriptions. However, some coding knowledge helps when reviewing and refining the generated code.",
  },
  {
    question: "How much does it cost?",
    answer:
      "OpenHands is free and open-source for self-hosting with your own API keys. We also offer Pro ($15/mo) and Pro+ ($25/mo) plans with platform credits, priority support, and advanced features. All plans support BYOK (Bring Your Own Key) for full control.",
  },
  {
    question: "Can I use OpenHands for commercial projects?",
    answer:
      "Yes! OpenHands is MIT licensed, which means you can use it for any personal or commercial project without restrictions. The code generated by AI is yours to use however you want.",
  },
];

export function BetaFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-20 px-6 bg-background-secondary">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <div className="inline-block px-4 py-2 bg-brand-500/10 border border-brand-500/30 rounded-full mb-4">
            <span className="text-sm font-semibold text-violet-500">FAQ</span>
          </div>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-foreground-secondary">
            Everything you need to know about OpenHands Beta
          </p>
        </div>

        <div className="space-y-4">
          {FAQ_ITEMS.map((item, index) => (
            <div
              key={index}
              className="bg-background-primary border border-border rounded-xl overflow-hidden hover:border-brand-500/50 transition-colors"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-background-tertiary/30 transition-colors"
              >
                <span className="text-lg font-semibold text-foreground pr-8">
                  {item.question}
                </span>
                <ChevronDown
                  className={`w-5 h-5 text-foreground-secondary flex-shrink-0 transition-transform duration-300 ${
                    openIndex === index ? "rotate-180" : ""
                  }`}
                />
              </button>
              <div
                className={`overflow-hidden transition-all duration-300 ${
                  openIndex === index ? "max-h-96" : "max-h-0"
                }`}
              >
                <div className="px-6 pb-5 text-foreground-secondary leading-relaxed">
                  {item.answer}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <p className="text-foreground-secondary mb-4">
            Have more questions?
          </p>
          <a
            href="mailto:support@all-hands.dev"
            className="text-violet-500 hover:text-brand-600 font-medium hover:underline"
          >
            Contact our support team →
          </a>
        </div>
      </div>
    </section>
  );
}

export default BetaFAQ;

