import React, { useState, useEffect } from "react";
import { MermaidDiagramViewer } from "./mermaid-diagram-viewer";
import {
  autoGenerateDiagram,
  generateOrchestrationFlow,
  generateApiSequenceDiagram,
} from "#/utils/mermaid-generator";
import { useMetaSOPOrchestration } from "#/hooks/use-metasop-orchestration";
import { applyAllNodeEnhancements } from "#/utils/diagram-node-enhancements";
import { CleanVisualAdapter } from "./clean-visualizations";
import { ModernFlowDiagram, CompactFlowView, TimelineView } from "./modern-flow-diagram";
import { parseArtifact } from "#/utils/artifact-parser";
import type { OrchestrationStep } from "#/types/metasop-artifacts";

interface OrchestrationDiagramPanelProps {
  className?: string;
  onNavigateToStep?: (stepId: string) => void;
  onClose?: () => void;
}

type DiagramTab =
  | "flow"
  | "agents"
  | "overview"
  | "architecture"
  | "api"
  | "ui"
  | "raw"
  | "database"
  | "timeline"
  | "classes";

export function OrchestrationDiagramPanel({
  className = "",
  onNavigateToStep,
  onClose,
}: OrchestrationDiagramPanelProps) {
  const [activeTab, setActiveTab] = useState<DiagramTab>("flow");
  const [diagrams, setDiagrams] = useState<
    Map<string, { type: string; mermaid: string }>
  >(new Map());

  // Real WebSocket integration - listen to MetaSOP orchestration events
  const { steps, isOrchestrating, hasSteps } = useMetaSOPOrchestration();

  // Generate diagrams whenever steps update
  useEffect(() => {
    if (!steps || steps.length === 0) return;

    // Generate diagrams for each step
    const newDiagrams = new Map<string, { type: string; mermaid: string }>();

    steps.forEach((step) => {
      if (step.artifact) {
        const diagram = autoGenerateDiagram(
          step.step_id,
          step.role,
          step.artifact,
        );
        if (diagram) {
          newDiagrams.set(step.step_id, diagram);
        }
      }
    });

    setDiagrams(newDiagrams);
  }, [steps]);

  // Apply node enhancements when diagram renders
  useEffect(() => {
    const applyEnhancements = () => {
      const svgElement = document.querySelector(
        ".mermaid-diagram-container svg",
      );
      if (svgElement && steps.length > 0) {
        applyAllNodeEnhancements(
          svgElement as SVGElement,
          steps,
          onNavigateToStep,
        );
      }
    };

    // Delay to ensure diagram is fully rendered
    const timeoutId = setTimeout(applyEnhancements, 200);
    return () => clearTimeout(timeoutId);
  }, [steps, activeTab, onNavigateToStep]);

  // Generate overview diagram
  const overviewDiagram = generateOrchestrationFlow(steps);

  // Find architecture diagram
  const architectureDiagram = Array.from(diagrams.values()).find(
    (d) => d.type === "architecture",
  )?.mermaid;

  // Generate API sequence diagram
  const apiDiagram = steps.find((s) =>
    s.role.toLowerCase().includes("architect"),
  )
    ? generateApiSequenceDiagram(
        steps.find((s) => s.role.toLowerCase().includes("architect"))
          ?.artifact || {},
      )
    : "";

  // Find UI component diagram
  const uiDiagram = Array.from(diagrams.values()).find(
    (d) => d.type === "ui-components",
  )?.mermaid;

  // Find specific diagram types
  const databaseDiagram = Array.from(diagrams.values()).find(
    (d) => d.type === "er-diagram",
  )?.mermaid;
  const timelineDiagram = Array.from(diagrams.values()).find(
    (d) => d.type === "gantt-chart",
  )?.mermaid;
  const classDiagram = Array.from(diagrams.values()).find(
    (d) => d.type === "class-diagram",
  )?.mermaid;

  const tabs: Array<{ id: DiagramTab; label: string; condition?: boolean }> = [
    { id: "flow" as DiagramTab, label: "Flow", condition: hasSteps },
    { id: "agents" as DiagramTab, label: "Agent Details", condition: hasSteps },
    { id: "overview" as DiagramTab, label: "Mermaid Overview" },
    {
      id: "architecture" as DiagramTab,
      label: "Architecture",
      condition: !!architectureDiagram,
    },
    { id: "api" as DiagramTab, label: "API Flow", condition: !!apiDiagram },
    { id: "ui" as DiagramTab, label: "UI Components", condition: !!uiDiagram },
    {
      id: "database" as DiagramTab,
      label: "Database",
      condition: !!databaseDiagram,
    },
    {
      id: "timeline" as DiagramTab,
      label: "Timeline",
      condition: !!timelineDiagram,
    },
    {
      id: "classes" as DiagramTab,
      label: "Classes",
      condition: !!classDiagram,
    },
    { id: "raw" as DiagramTab, label: "Raw JSON" },
  ].filter((tab) => tab.condition === undefined || tab.condition);

  return (
    <div
      className={`orchestration-diagram-panel flex flex-col h-full bg-background-secondary rounded-lg border border-border ${className}`}
    >
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-border dark:border-border bg-background-secondary">
        <div className="flex items-center gap-3">
          {onClose && (
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg hover:bg-background-tertiary/70 transition-colors"
              title="Close panel"
            >
              <svg
                className="w-5 h-5 text-foreground-secondary"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M15 19l-7-7 7-7"
                />
              </svg>
            </button>
          )}
          <svg
            className="w-5 h-5 text-primary-500"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
            />
          </svg>
          <h3 className="text-lg font-semibold text-foreground">
            Orchestration Diagrams
          </h3>
          {isOrchestrating && (
            <span className="ml-2 px-2 py-1 text-xs bg-blue-900 text-blue-200 rounded-full animate-pulse">
              Live
            </span>
          )}
        </div>
        <div className="text-sm text-foreground-secondary">
          {steps.length > 0
            ? `${steps.length} steps`
            : "Waiting for orchestration..."}
        </div>
      </div>

      {/* Pass to CodeAct Button */}
      {hasSteps && (
        <div className="px-4 pt-4 pb-2">
          <button
            onClick={() => {
              // TODO: Implement Pass to CodeAct functionality
              console.log("Pass to CodeAct clicked with steps:", steps);
            }}
            className="w-full bg-gradient-to-r from-emerald-500 to-green-600 text-white font-semibold py-3 px-4 rounded-lg hover:from-emerald-600 hover:to-green-700 transition-all duration-200 shadow-lg hover:shadow-xl flex items-center justify-center gap-2"
          >
            <svg
              className="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            Pass to CodeAct
          </button>
        </div>
      )}

      {/* Tabs */}
      <div className="flex gap-2 p-2 border-b border-border overflow-x-auto bg-background-secondary">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 whitespace-nowrap ${
              activeTab === tab.id
                ? "bg-primary-500 text-white shadow-md"
                : "bg-background-tertiary/70 text-foreground-secondary hover:bg-background-tertiary"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-4 bg-background-secondary">
        {activeTab === "flow" && (
          <div className="h-full">
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              Modern Orchestration Flow
              {isOrchestrating && (
                <span className="ml-2 text-xs text-violet-500">
                  ● Live Updates
                </span>
              )}
            </h4>
            {steps.length > 0 ? (
              <ModernFlowDiagram
                steps={steps.map(convertToOrchestrationStep)}
                status={isOrchestrating ? "in_progress" : "idle"}
                onStepClick={(step) => onNavigateToStep?.(step.id)}
                layout="vertical"
                animated={true}
                showControls={true}
              />
            ) : (
              <div className="flex flex-col items-center justify-center text-foreground-secondary py-12 bg-background-secondary">
                <svg
                  className="w-16 h-16 mb-4 opacity-50"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
                  />
                </svg>
                <p className="text-sm">No orchestration flow available</p>
                <p className="text-xs mt-2 opacity-70">
                  Enable MetaSOP and send a message to start orchestration
                </p>
              </div>
            )}
          </div>
        )}

        {activeTab === "agents" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              Agent Artifact Details
            </h4>
            {steps.length > 0 ? (
              <div className="space-y-6">
                {steps.map((step) => (
                  step.artifact && (
                    <div key={step.step_id}>
                      <CleanVisualAdapter
                        artifact={parseArtifact(step.artifact, mapRoleString(step.role))}
                        animated={true}
                        onInteraction={(action, data) => {
                          console.log("Interaction:", action, data);
                        }}
                      />
                    </div>
                  )
                ))}
                {steps.every((s) => !s.artifact) && (
                  <div className="text-center text-foreground-secondary py-8 bg-background-secondary">
                    <p className="text-sm">Waiting for agents to generate artifacts...</p>
                  </div>
                )}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center text-foreground-secondary py-12 bg-background-secondary">
                <p className="text-sm">No agent details available</p>
                <p className="text-xs mt-2 opacity-70">
                  Agents will display their work here as they complete tasks
                </p>
              </div>
            )}
          </div>
        )}

        {activeTab === "overview" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              Orchestration Flow
              {isOrchestrating && (
                <span className="ml-2 text-xs text-violet-500">
                  ● In Progress
                </span>
              )}
            </h4>
            {overviewDiagram && steps.length > 0 ? (
              <MermaidDiagramViewer
                diagram={overviewDiagram}
                onNodeClick={onNavigateToStep}
                exportFilename="orchestration-overview"
              />
            ) : (
              <div className="flex flex-col items-center justify-center text-foreground-secondary py-12 bg-background-secondary">
                <svg
                  className="w-16 h-16 mb-4 opacity-50"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
                  />
                </svg>
                <p className="text-sm">No orchestration data available</p>
                <p className="text-xs mt-2 opacity-70">
                  Enable SOP and send a message to start orchestration
                </p>
              </div>
            )}
          </div>
        )}

        {activeTab === "architecture" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              System Architecture
            </h4>
            {architectureDiagram ? (
              <MermaidDiagramViewer
                diagram={architectureDiagram}
                exportFilename="system-architecture"
              />
            ) : (
              <div className="text-center text-foreground-secondary py-8 bg-background-secondary">
                Waiting for architect step to complete...
              </div>
            )}
          </div>
        )}

        {activeTab === "api" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              API Sequence Flow
            </h4>
            {apiDiagram ? (
              <MermaidDiagramViewer
                diagram={apiDiagram}
                exportFilename="api-sequence"
              />
            ) : (
              <div className="text-center text-foreground-secondary py-8 bg-background-secondary">
                No API specifications available
              </div>
            )}
          </div>
        )}

        {activeTab === "ui" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              UI Component Tree
            </h4>
            {uiDiagram ? (
              <MermaidDiagramViewer
                diagram={uiDiagram}
                exportFilename="ui-components"
              />
            ) : (
              <div className="text-center text-foreground-secondary py-8 bg-background-secondary">
                No UI design specifications available
              </div>
            )}
          </div>
        )}

        {activeTab === "database" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              Database Schema (ER Diagram)
            </h4>
            {databaseDiagram ? (
              <MermaidDiagramViewer
                diagram={databaseDiagram}
                exportFilename="database-schema"
              />
            ) : (
              <div className="text-center text-foreground-secondary py-8 bg-background-secondary">
                No database schema available
              </div>
            )}
          </div>
        )}

        {activeTab === "timeline" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              Project Timeline (Gantt Chart)
            </h4>
            {timelineDiagram ? (
              <MermaidDiagramViewer
                diagram={timelineDiagram}
                exportFilename="project-timeline"
              />
            ) : (
              <div className="text-center text-foreground-secondary py-8 bg-background-secondary">
                No timeline data available
              </div>
            )}
          </div>
        )}

        {activeTab === "classes" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              Class Diagram
            </h4>
            {classDiagram ? (
              <MermaidDiagramViewer
                diagram={classDiagram}
                exportFilename="class-diagram"
              />
            ) : (
              <div className="text-center text-foreground-secondary py-8 bg-background-secondary">
                No class structure available
              </div>
            )}
          </div>
        )}

        {activeTab === "raw" && (
          <div>
            <h4 className="text-sm font-semibold text-foreground-secondary mb-4">
              Raw JSON Data
            </h4>
            <div className="space-y-4">
              {steps.map((step) => (
                <div
                  key={step.step_id}
                  className="bg-white dark:bg-background-secondary rounded-lg p-4 border border-border dark:border-border"
                >
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-medium text-foreground">
                      {step.role}
                    </span>
                    <span
                      className={`text-xs px-2 py-1 rounded ${
                        step.status === "success"
                          ? "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200"
                          : step.status === "running"
                            ? "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200"
                            : "bg-background-tertiary text-foreground-secondary"
                      }`}
                    >
                      {step.status}
                    </span>
                  </div>
                  {step.artifact && (
                    <pre className="text-xs text-foreground-secondary/70 dark:text-foreground-secondary overflow-auto max-h-64 bg-background-tertiary p-2 rounded">
                      {JSON.stringify(step.artifact, null, 2)}
                    </pre>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// Helper function to convert MetaSOP hook step format to OrchestrationStep
function convertToOrchestrationStep(step: any): OrchestrationStep {
  return {
    id: step.step_id || step.id || "",
    role: mapRoleString(step.role),
    title: step.title || step.role || "Untitled Step",
    description: step.description,
    status: mapStatusString(step.status),
    artifact: step.artifact ? parseArtifact(step.artifact, mapRoleString(step.role)) : undefined,
    started_at: step.started_at,
    completed_at: step.completed_at,
    error: step.error,
    progress: step.progress,
  };
}

function mapRoleString(role: string): "product_manager" | "architect" | "engineer" | "qa" {
  const roleLower = role.toLowerCase().replace(/[_-]/g, "");
  if (roleLower.includes("product") || roleLower.includes("pm")) return "product_manager";
  if (roleLower.includes("architect") || roleLower.includes("arch")) return "architect";
  if (roleLower.includes("engineer") || roleLower.includes("eng")) return "engineer";
  if (roleLower.includes("qa") || roleLower.includes("test")) return "qa";
  return "engineer"; // default
}

function mapStatusString(status: string): "pending" | "in_progress" | "complete" | "blocked" {
  const statusLower = status.toLowerCase().replace(/[_-]/g, "");
  if (statusLower === "complete" || statusLower === "completed" || statusLower === "done" || statusLower === "success") return "complete";
  if (statusLower === "inprogress" || statusLower === "running" || statusLower === "active") return "in_progress";
  if (statusLower === "blocked" || statusLower === "failed" || statusLower === "error") return "blocked";
  return "pending";
}
