import {
  autoGenerateDiagram,
  generateApiSequenceDiagram,
  generateOrchestrationFlow,
} from "#/utils/mermaid-generator";
import { parseArtifact } from "#/utils/artifact-parser";
import type { OrchestrationStep } from "#/types/metasop-artifacts";

export type DiagramTab =
  | "flow"
  | "agents"
  | "overview"
  | "architecture"
  | "api"
  | "ui"
  | "raw"
  | "database"
  | "timeline"
  | "classes";

export interface GeneratedDiagramEntry {
  type: string;
  mermaid: string;
}

export interface OrchestrationDiagramState {
  diagrams: Map<string, GeneratedDiagramEntry>;
  overviewDiagram?: string;
  architectureDiagram?: string;
  apiDiagram?: string;
  uiDiagram?: string;
  databaseDiagram?: string;
  timelineDiagram?: string;
  classDiagram?: string;
  tabs: Array<{ id: DiagramTab; label: string }>;
}

type StepInput = Record<string, any>;

const findDiagramByType = (
  diagrams: Map<string, GeneratedDiagramEntry>,
  type: string,
) =>
  Array.from(diagrams.values()).find((diagram) => diagram.type === type)
    ?.mermaid;

export function buildOrchestrationDiagramState(
  steps: ReadonlyArray<StepInput> | undefined,
  hasSteps: boolean,
): OrchestrationDiagramState {
  const safeSteps = Array.isArray(steps) ? steps : [];

  const diagrams = new Map<string, GeneratedDiagramEntry>();

  safeSteps.forEach((step) => {
    if (!step?.artifact) {
      return;
    }

    const diagram = autoGenerateDiagram(
      step.step_id ?? step.id,
      step.role,
      step.artifact,
    );
    if (diagram?.mermaid) {
      diagrams.set(step.step_id ?? step.id ?? "", diagram);
    }
  });

  const overviewDiagram =
    safeSteps.length > 0 ? generateOrchestrationFlow(safeSteps) : undefined;

  const architectureDiagram = findDiagramByType(diagrams, "architecture");
  const uiDiagram = findDiagramByType(diagrams, "ui-components");
  const databaseDiagram = findDiagramByType(diagrams, "er-diagram");
  const timelineDiagram = findDiagramByType(diagrams, "gantt-chart");
  const classDiagram = findDiagramByType(diagrams, "class-diagram");

  const architectStep = safeSteps.find(
    (step) =>
      typeof step?.role === "string" &&
      step.role.toLowerCase().includes("architect"),
  );

  const apiDiagram = architectStep
    ? generateApiSequenceDiagram(architectStep.artifact ?? {})
    : undefined;

  const tabs: Array<{ id: DiagramTab; label: string }> = [
    { id: "flow" as DiagramTab, label: "Flow" },
    { id: "agents" as DiagramTab, label: "Agent Details" },
    { id: "overview" as DiagramTab, label: "Mermaid Overview" },
    { id: "architecture" as DiagramTab, label: "Architecture" },
    { id: "api" as DiagramTab, label: "API Flow" },
    { id: "ui" as DiagramTab, label: "UI Components" },
    { id: "database" as DiagramTab, label: "Database" },
    { id: "timeline" as DiagramTab, label: "Timeline" },
    { id: "classes" as DiagramTab, label: "Classes" },
    { id: "raw" as DiagramTab, label: "Raw JSON" },
  ].filter((tab) => {
    switch (tab.id) {
      case "flow":
      case "agents":
        return hasSteps;
      case "architecture":
        return Boolean(architectureDiagram);
      case "api":
        return Boolean(apiDiagram);
      case "ui":
        return Boolean(uiDiagram);
      case "database":
        return Boolean(databaseDiagram);
      case "timeline":
        return Boolean(timelineDiagram);
      case "classes":
        return Boolean(classDiagram);
      default:
        return true;
    }
  });

  return {
    diagrams,
    overviewDiagram,
    architectureDiagram,
    apiDiagram,
    uiDiagram,
    databaseDiagram,
    timelineDiagram,
    classDiagram,
    tabs,
  };
}

export function convertToOrchestrationStep(step: StepInput): OrchestrationStep {
  return {
    id: step.step_id || step.id || "",
    role: mapRoleString(step.role ?? ""),
    title: step.title || step.role || "Untitled Step",
    description: step.description,
    status: mapStatusString(step.status ?? ""),
    artifact: step.artifact
      ? parseArtifact(step.artifact, mapRoleString(step.role ?? ""))
      : undefined,
    started_at: step.started_at,
    completed_at: step.completed_at,
    error: step.error,
    progress: step.progress,
  };
}

export function mapRoleString(
  role: string,
): "product_manager" | "architect" | "engineer" | "qa" {
  const roleLower = role.toLowerCase().replace(/[_-]/g, "");
  if (roleLower.includes("product") || roleLower.includes("pm"))
    return "product_manager";
  if (roleLower.includes("architect") || roleLower.includes("arch"))
    return "architect";
  if (roleLower.includes("engineer") || roleLower.includes("eng"))
    return "engineer";
  if (roleLower.includes("qa") || roleLower.includes("test")) return "qa";
  return "engineer";
}

export function mapStatusString(
  status: string,
): "pending" | "in_progress" | "complete" | "blocked" {
  const statusLower = status.toLowerCase().replace(/[_-]/g, "");
  if (["complete", "completed", "done", "success"].includes(statusLower)) {
    return "complete";
  }
  if (["inprogress", "running", "active"].includes(statusLower)) {
    return "in_progress";
  }
  if (["blocked", "failed", "error"].includes(statusLower)) {
    return "blocked";
  }
  return "pending";
}
